### ISSUE TITLE
[API] Add a .env.sample file

### ISSUE THREAD

**Issue by dersonsena** [sigalei/sigalei-stack#27]
It is a good practice to add a `.env.sample` file so that a new developer, or when the project clone is done, knows which environment variables the project needs.

The idea is that the `.env.sample` file enters the version control with its empty values or some already filled, as long as no sensitive data is shared.

**Comment by caioflores** [comment]
Interesting, I never thought about that! Is it a common practice? Do you know any project that uses this practice or some reference? I think it's a good idea!

**Comment by dersonsena** [comment]
Is @caioflores , is a common practice in both backend and frontend projects. Not only for `.env` files, but this approach to` docker-compose.yml` and others is also very common. But this is an approach that I find more productive than creating those `.test`,` .production`.

I'll show you some references that use this practice:

[https://github.com/laravel/laravel](https://github.com/laravel/laravel) -> .env.sample

**Comment by caioflores** [comment]
Great! Thank you for the reference, I think this would be a great improvement.

**Comment by dersonsena** [comment]
Can I implement this ?

**Comment by caioflores** [comment]
Sure!

**Comment by dersonsena** [comment]
Ok @caioflores , I'm working on it!

**Comment by dersonsena** [comment]
PR #36

**Comment by caioflores** [comment]
Great work @dersonsena ! PR approved.
