### ISSUE TITLE
Add a .editorconfig file in project

### ISSUE THREAD

**Issue by dersonsena** [sigalei/sigalei-stack#28]
When we have a team of many developers where each uses a different IDE or text editor, it is a good practice to have a `.editorconfig` file to standardize certain things, such as:

- Always insert a line at the end of the files;
- Size and type of indentations;
- Standard Charset;

There are other useful parameters to help with code styling. More details can be found at [https://editorconfig.org](https://editorconfig.org)

**Comment by caioflores** [comment]
Great! I already saw this in some projects, but how it works with eslint/prettier? Can we use them all? Are they complementary?
Here in sigalei, to work in our JS stack you have to use a IDE that works well with our lint/prettier rules.

**Comment by dersonsena** [comment]
Yes @caioflores , it can be used in conjunction with the linters. The EditorConfig focuses on applying minimal rules at the IDE level, as I mentioned before. Linters are much more advanced and are focused on maintaining a code pattern between devs

**Comment by caioflores** [comment]
Now I got it @dersonsena, so I think it would be a good improvement!

**Comment by dersonsena** [comment]
I'm working on it.

**Comment by dersonsena** [comment]
PR #37

**Comment by kerollaine** [comment]
I also think it would be good to add the .editorconfig to the API project. I'm working on it!

**Comment by kerollaine** [comment]
PR #40

**Comment by dersonsena** [comment]
@kerollaine I already implemented this and it's in the PR #37

**Comment by kerollaine** [comment]
Hi @dersonsena! I saw the PR #37, so help me to understanding better how EditorConfig works.

The commit 48dc6a31e add a `.editorconfig` file inside `/react/` directory, with `root = true` what means that this is the top-most EditorConfig file, right?

Considering this, I thought it necessary to create a file for the backend too (`/api`). Isn't?

**Comment by dersonsena** [comment]
Yes @kerollaine , I agree. I don't have saw the folder where you inserted the `.editorconfig` file, I'm sorry! So, made sense so much submit the PR #40 =)

**Comment by caioflores** [comment]
Nice! I approved both PRs, great job!
