### ISSUE TITLE
Folder structure suggest

### ISSUE THREAD

**Issue by dersonsena** [sigalei/sigalei-stack#32]
It's notorious that the `src` directory is pretty messy, where everything has been thrown there in a disorganized way.

Initially I suggest that folders be created:

- `src/components`: as the project has few components, it could be placed here `Login.js`, `Task.js`, `User.js` and `UserList.js`. If the project grows, the ideal would be to create a `domains` directory and within them to create other directories with specific contexts;

- `src/assets`: here will be images and non-static style files, that is, they went through the webpack build process, such as `App.css`, `index.css`, `logo.svg`;

- The `commitMutation.js`,` CreateQueryRender.js`, `CreateRelayEnviroment`,` fetchQuery.js` files to be moved to the existing `src/utils` directory;

I believe that by following these rules we will have a more organized and scalable structure;

**Comment by rafaelangical** [comment]
I'm working on it

**Comment by rafaelangical** [comment]
PR #35
