### ISSUE TITLE
Two-way-data-binding in Login.js

### ISSUE THREAD

**Issue by dersonsena** [sigalei/sigalei-stack#33]
I saw that in the component `Login.js` we have this code snippet in lines 27 and 28:

```js
const email = document.getElementById ("email"). value;
const password = document.getElementById ("password"). value;
```

React takes an approach of working with states, so we do not have to manipulate the DOM directly for several reasons.

The ideal here would be to create two properties in the component state representing the email and password and to apply the Two Way Data Binding of these properties with the form fields.

**Comment by rafaelangical** [comment]
I'm working on it

**Comment by dersonsena** [comment]
@rafaelangica I'm already working in the task

**Comment by rafaelangical** [comment]
Ok @dersonsena

**Comment by caioflores** [comment]
Ok @dersonsena , just remeber to comment on the issues that you are working on plz.

**Comment by dersonsena** [comment]
Oh, sorry @caioflores , I realy forgot! It will not happen again =)

**Comment by dersonsena** [comment]
PR #34

**Comment by caioflores** [comment]
@dersonsena I reviewed the PR with one suggestion.

**Comment by dersonsena** [comment]
@caioflores can I close this issue ?

**Comment by caioflores** [comment]
Yes, I forgot to do it.
