### ISSUE TITLE
Add the PropTypes package for props validation

### ISSUE THREAD

**Issue by dersonsena** [sigalei/sigalei-stack#38]
Although it does not currently have many components props, it is **extremely necessary** that it has a validation and minimum typing for the components.

With the use of Proptypes it becomes more explicit to know what the props that the component can receive, what the required ones and also the types of data that each one must receive.

React.js natively does not bring this, and for this the Facebook team has developed a package called [PropTypes](https://github.com/facebook/prop-types).

**Comment by dersonsena** [comment]
I'm working on it!

**Comment by dersonsena** [comment]
PR #39

**Comment by caioflores** [comment]
Great suggestion, we already use it in our production application and we can get many bugs while developing, it's really helpful.

**Comment by caioflores** [comment]
I reviewed it with some comments.
