### ISSUE TITLE
Move the API Base URL to a .env file

### ISSUE THREAD

**Issue by dersonsena** [sigalei/sigalei-stack#42]
The base URL of an API is considered an environment variable because it tends to change depending on the environment that the application is in. React.js, in conjunction with node.js, can read environment variables prefixed with `REACT_APP_` in an .env file.

This approach helps a lot in the application setup and also in the CI/CD process. My suggestion would be to insert an environment variable named `REACT_APP_API_BASE_URL` with the value `http://localhost:5000` as below:

```
REACT_APP_API_BASE_URL=http://localhost:5000
```

And in the `src/CreateRelayEnviroment.js` file on `line 4` change to:

```js
return fetch(`${REACT_APP_API_BASE_URL}/graphql`, { ... })
```

**Comment by dersonsena** [comment]
@caioflores I going implement it now.

**Comment by caioflores** [comment]
Ok @dersonsena, I totally agree!

**Comment by dersonsena** [comment]
PR #43
